### ISSUE TITLE
Scientist Upgrades Affecting Enemies???

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#104]
I could not help but notice that enemies have become significantly stronger since recent updates, so much so that some beta testers are getting softlocked at their levels - unable to progress due to the stronger enemies, and some few struggling to complete levels. Aside from the new class of enemies with the crimson red icon, was there a change in enemy ship builds that we are not aware of? We also suspect that the scientist upgrades are affecting enemies due to their increased strength, so it would be much appreciated if these are clarified, thank you.

**Comment by PavelZinchenko** [comment]
I've adjusted the settings for levels above 200. Now, there can be up to 12 enemies at the same time instead of 5, more flagships than before, and hardcore ship builds (red icons). Naturally, these changes have made the levels more challenging. However, enemies don't use upgrades nor other bonuses. They only have an attack and defense bonus that gradually increases with the level number, which is written in the level description.
