### ISSUE TITLE
Heavy EMP Nuke Is Unusable

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#115]
The Heavy EMP Nuke is currently unusable as it suffers from multiple factors. One issue is it being a Missile Type - literally the most useless weapon type in the game, due to bullet collisions to multiple environmental factors.

It wouldn't reach its target simply because it would just get shot down/crash into asteroids and loot on its way to the target. There's also a very high possibility of it just exploding in your face when an enemy ship is attacking you. Its projectile speed is extremely slow (even with gold +100% projectile speed mod), it takes more than 6 seconds for it to be far away enough from your ship to not get caught in the AoE if it does explode early (spoiler alert: it will always explode early).

But the worst issue of all is that friendly EMP Nuke ALSO collides with your own/friendly projectiles. So, not only that enemies can shoot it down, your own ship/your own mercenaries can also shoot your own EMP Nuke! So the most common scenario that happens when using EMP Nukes is that it just simply explodes in your face. It is currently more of a liability than actual help in the field, double the uselessness if used by AI as the AI is terrible in using it.

It needs to be rebalanced if this weapon would want to see any actual use.

**Comment by Inedilarion** [comment]
I’ll also add that when used successfully, this rocket launcher completely destroys the usefulness of drone carriers (which are already suffering) and component shields (which are already relevant only on one ship in the game and on one base). And ordinary ships are not very vulnerable to it due to their speed

Добавлю ещё что при успешном применении эта ракетница полностью уничтожает смысл дроновозов (которые и так страдают) и компонентных щитов (которые и так актуальны только на одном корабле в игре и на одной базе). А обычные корабли для неё не очень уязвимы благодаря своей скорости

**Comment by TaipionsSalemClient** [comment]
yes

in short, EMP Nuke must:
- not be a "hold to fire, explode on button release"-weapon, that sucks a lot
- not do friendly fire
- be homing
- not be a missile, as it is too easy to destroy
- be nerfed in shield dmg


Both the player and AI should be able to use the weapon, and as it is now, literally every detail on it is designed to make it unusable.
The shield dmg is a bit too high and should be lowered, but even the high dmg does not justify its complete uselessness in every other aspect.
The area effect could be a bit bigger and a lot longer lasting.
