### ISSUE TITLE
Чересчур имбовый перк наёмников

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#178]
Новый перк наёмников ломает баланс игры, тк его можно поставить на титаны. Люди могут набить весь флот титанами, а с этим перком получится 8 титанов. Представьте себе по два Wormship, два Scarab, две Syberia и два Harbour. Это хаос. Можно сделать ограничение: чтобы перк был только у кораблей до линкоров включительно.

**Comment by Thirteen0130** [comment]
![1714074580900](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164494313/6b47e231-3faa-4811-be67-410109aaa6f9)

**Comment by magne00** [comment]
This perk needs to cut ship stats by half.

**Comment by Thirteen0130** [comment]
Мне хотелось бы, чтобы сила двойника была бы 50% от оригинала, но перк был доступен и на линкорах

**Comment by vlad-ultramarine** [comment]
даже если будет 50% то на линкорах это все равно сильно

**Comment by PavelZinchenko** [comment]
I'm thinking about one or more of these changes:
- make it unavailable for big ships
- increase (or double) CP cost
- decrease ship stats
- make it rare and only available for mercs found in exploration or slave market

**Comment by Thirteen0130** [comment]
Я согласен с уменьшением статов кораблей и  убрать перк на большие корабли

**Comment by vlad-ultramarine** [comment]
"slave market"?
ты имеешь ввиду корабль rhino где можно купить наемников?

**Comment by MisterN13** [comment]
> I'm thinking about one or more of these changes:
> 
> * make it unavailable for big ships
> * increase (or double) CP cost
> * decrease ship stats
> * make it rare and only available for mercs found in exploration or slave market

Можно оставить все как есть . Только сделать его несовместимым с перком специалист. Тогда игрок будет думать что ему выбрать специалиста или двойника

**Comment by vlad-ultramarine** [comment]
> > I'm thinking about one or more of these changes:
> > 
> > * make it unavailable for big ships
> > * increase (or double) CP cost
> > * decrease ship stats
> > * make it rare and only available for mercs found in exploration or slave market
> 
> Можно оставить все как есть. Только сделать его несовместимым с перком специалист. Тогда игрок будет думать что ему выбрать специалиста или двойника

с ума сошел? что выбрать: специалиста на титана или двойник титана, конечно же двойника тут и думать не надо, имба

**Comment by PavelZinchenko** [comment]
> "slave market"? ты имеешь ввиду корабль rhino где можно купить наемников?

рынок рабов на pvp карте где можно покупать капитанов "вслепую" за токены. появится в следующем обновлении

**Comment by IsmollCheeKen** [comment]
I vouch for making it unavailable for Battleships and above, and with a penalty for increasing CP cost by 50% (Rounded up).

This makes it have an overall net positive. To example: instead of having Leshy and Space Invader in the fleet, where Space Invader is weaker, you could instead have 2 Leshy - not only you have the luxury of replacing a weaker ship with a stronger one from this, you also only need to spend additional CP that is worth half a Cruiser.

**Comment by Inedilarion** [comment]
> * make it unavailable for big ships
Right now the weakest class is cruisers (in terms of power to command points required), so limiting the new perk to them looks good. But this will also strengthen super-powerful destroyers (Raptor, Object 18, ISS Gunboat, Leech MK2), which are already more powerful than all common cruisers in terms of command points. So I’m not sure that such a restriction will lead to anything other than huge swarms of small ships

> * ease (or double) CP cost
Double CP seems like a fair option. Replacing one captain perk with the ability to set up a duplicate of the desired strong ship. The only not very pleasant moment is that this will reduce the need to use different ships

> I vouch for making it unavailable for Battleships and above, and with a penalty for increasing CP cost by 50% (Rounded up).
So, frigate for 2 CP, destroyer for 3 CP, cruiser for 5 CP. Quite strange and powers up more destroyers than cruisers...

> * decrease ship stats
> * Можно оставить все как есть. Только сделать его несовместимым с перком специалист. Тогда игрок будет думать что ему выбрать специалиста или двойника
The specialist increases the ship's parameters by 1.5 times, the new perk more than doubles, taking into account the increase in the weapon's damage zone due to the appearance of the second ship. Reducing the attack and defense stats to 70% will make the new perk approximately equal in effectiveness to the specialist and its good alternative

> * make it rare and only available for mercs found in exploration or slave market
This will not solve the problem, sooner or later everyone will get captains for all their ships with this perk. But you can combine it with the previous point, then it will be interesting

On my own behalf, I’ll also add an option to make the second ship non-respawning. Although this is not a very good option, since it will be good to strengthen only the most durable ships, but this can diversify the player's experience when building a ship and fleet

**Comment by TaipionsSalemClient** [comment]
> I'm thinking about one or more of these changes:
> 
> * make it unavailable for big ships
> * increase (or double) CP cost
> * decrease ship stats
> * make it rare and only available for mercs found in exploration or slave market

1: make it unavailable for "big" ships
- it will still be too OP, smaller ships cost less CP, a double raptor, covi, velez, priest... would still be way too OP

2: increase (or double) CP cost
- doubling CP cost simply means you can have two of your favourite ships, reducing ship variety, again not good

3: decrease ship stats
- two ships with half stats each (dmg, hp) ... might work, but I still don't see the value in this

4: make it rare
- hell no, forcing people to grind explorations or spam "refresh" on the merc shop for literal hours... hell no, that'd be the worst


Conclusion:
- This perk is inherently too OP
- including nerfs/trade-offs in the perk, like halving stats, is difficult to balance
- Having all ships doubled seems dumb as well, it just crowds up the map, especially arena, that sounds bad
- There is literally no necessity for this perk

Solution:
- remove the perk
- replace it with something else, if this perk was a replacement for rear admiral, I'd recommend something like +15% dmg and +15% def perk, as was suggested as adequate replacement for rear admiral already

**Comment by PavelZinchenko** [comment]
I've adjusted the CP cost to 2*CP - 1, making it free for frigates and nearly ineffective for titans. I don't intend to remove it, as it's not meant to replace the rear admiral. Per the suggestions in the discussion thread, I've replaced it with veteran.

**Comment by magne00** [comment]
Reducing the ship and clone attack/hp by half is the only way to make this work without breaking the game. This way, only ships that are equipped with utility/support weapons (emps, plasma webs, etc.) can fully utilize this perk.
