### ISSUE TITLE
(Ошибка) Кнопка "Выходите все" Не работает

### ISSUE THREAD

**Issue by Bezbasheniy** [PavelZinchenko/event-horizon-frontier-builds#233]
Протэстировал кнопку "Выходите все" На 10 этапах. Что с кнопкой, что без неë скорость спавна никак не изменилась.

**Comment by Thirteen0130** [comment]
Допустим, на уровне 199 скорость без кнопки была 1X, с кнопкой на том же 199 уровне была 2X. После 200 уровня скорость также 2X(тк они уже выходят все), как если бы с кнопкой. А этой обновой (лично я хотел), чтобы скорость с кнопкой после 200 уровня была 3X. То есть к первоначальной скорости спавна добавлялось бы ещё. Я ведь писал, что скорость спавна маленькая и муторная и надо бы увеличить ещё кнопкой, но ,видимо, неправильно выразился, и меня не поняли. (Выглядит запутанно, но надеюсь, разработчик меня поймёт)

Let's say at level 199 the speed without the button was 1X, with the button at the same level 199 it was 2X. After level 200, the speed is also 2X (because they are already coming out all), as if with a button. And with this update (personally, I wanted) the speed with the button after level 200 to be 3X. That is, more would be added to the initial spawn rate. After all, I wrote that the speed of spawn is small and dreary and it would be necessary to increase it with a button, but, apparently, I expressed myself incorrectly, and they did not understand me. (It looks confusing, but I hope the developer will understand me) 

(Ps.I warn you: the translator is clumsy)

**Comment by Thirteen0130** [comment]
Допустим, на уровне 199 скорость без кнопки была 1X, с кнопкой на том же 199 уровне была 2X. После 200 уровня скорость также 2X(тк они уже выходят все), как если бы с кнопкой. А этой обновой (лично я хотел), чтобы скорость с кнопкой после 200 уровня была 3X. То есть к первоначальной скорости спавна добавлялось бы ещё. Я ведь писал, что скорость спавна маленькая и муторная и надо бы увеличить ещё кнопкой, но ,видимо, неправильно выразился, и меня не поняли. (Выглядит запутанно, но надеюсь, разработчик меня поймёт)

Let's say at level 199 the speed without the button was 1X, with the button at the same level 199 it was 2X. After level 200, the speed is also 2X (because they are already coming out all), as if with a button. And with this update (personally, I wanted) the speed with the button after level 200 to be 3X. That is, more would be added to the initial spawn rate. After all, I wrote that the speed of spawn is small and dreary and it would be necessary to increase it with a button, but, apparently, I expressed myself incorrectly, and they did not understand me. (It looks confusing, but I hope the developer will understand me) 

(Ps.I warn you: the translator is clumsy)

**Comment by Bezbasheniy** [comment]
Лично мое мнение чтобы добавили множители 5 и 10 тогда будет какая никакая динамика. А так до спутников на 666 можно два года добираться.

**Comment by PavelZinchenko** [comment]
By default, there are 12 enemies on the battlefield. Additional enemies spawn every 10 seconds or immediately if there are fewer than 12 enemies. When you press a button, the maximum number of enemies on the battlefield increases to 30, and new enemies spawn immediately as soon as you kill any.

**Comment by PavelZinchenko** [comment]
Increasing the number of enemies further may cause lags

**Comment by Bezbasheniy** [comment]
> По умолчанию на поле боя 12 врагов. Дополнительные враги появляются каждые 10 секунд или сразу, если врагов меньше 12. Когда вы нажимаете кнопку, максимальное количество врагов на поле битвы увеличивается до 30, а новые враги появляются сразу же, как только вы их убиваете.

К сожалению гдето есть ошибка, так как количество врагов проседает до 1 даже с нажатой кнопкой. Во всяком случае так происходит на уровнях выше 200.

**Comment by PavelZinchenko** [comment]
У меня такого не случалось. Убавил минимальную задержку между спавном врагов с 0.5 сек до 0.1 сек. Надеюсь поможет.

I haven't encountered this during testing. I've reduced the minimum delay between enemy spawns from 0.5 seconds to 0.1 seconds. I hope this helps.

**Comment by Bezbasheniy** [comment]
> У меня такого не случалось. Убавил минимальную задержку между спавном противником с 0,5 до 0,1 сек. Надеюсь поможет.
> 
> За время тестирования я с этим не столкнулся. Я уменьшил минимальную задержку между появлением врагов с 0,5 секунды до 0,1 секунды. Надеюсь, это поможет.

Огромное спасибо. Действительно помогло.
