### ISSUE TITLE
invader ship can't be destroyed 

### ISSUE THREAD

**Issue by vlad-ultramarine** [PavelZinchenko/event-horizon-frontier-builds#37]
корабль инвайдер невозможно уничтожить, хоть цифры урона показывают получаемый урон его полоска здоровья вообще не двигается

**Comment by PavelZinchenko** [comment]
Так и было задумано. Эффект дает не корабль а капитан. Корабль довольно слабый и мало что может сделать, так что это не должно заметно менять расклад сил.

**Comment by vlad-ultramarine** [comment]
не думаю что нужно делать это настолько мощно, он просто отвлекает все мощные корабли на себя и впитывает урон. Возможно резист в 95% ко всем видам урона и ×5/×10 очки здоровья более сбалансирово

**Comment by vlad-ultramarine** [comment]
если это эффект пилота, то я могу поставить ему любой крейсер со сборкой без брони и получить неубиваемую машину уничтожения, например тот же rattletrap с тяжёлой торпедой антиматерии +200% урона +20 (которую я давно так улучшил)

**Comment by Tree3324417** [comment]
I do believe that the invader is not a weak ship by itself even without the immunity. It is used plenty in arena already, even before this immunity change. Making it invincible is unbalanced and potentially forcing p2w - I would recommend undoing this change.

**Comment by imverybadatnames** [comment]
Pavel, please revert invader's immortalitt. the invader can mount 2 heavy acid torpedoes, as it will break the balance of arena. The invader can be used to distract several mercenaries and be able to kill them. Combined with the fact that the Pavel Zinchenko pilot costs only 1 command point, this will break the entire balance of the game. I know that the Pavel pilot is supposed to be good because of gold supporter perk, but please, remove/change the immortality.

**Comment by PavelZinchenko** [comment]
It was like that since it was introduced. Not sure why became an issue only now. But alright, I'll change it.

**Comment by vlad-ultramarine** [comment]
Я помню чтобы он раньше был бессмертным, он спокойно убивался.

**Comment by PavelZinchenko** [comment]
This is because Captain Perks had not been stored in the Arena Fleet before, so the invaders in the arena weren't immortal. However, the invaders that players had were.
