### ISSUE TITLE
Resistance Perk Effects Are Too Strong

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#45]
The new effects of the Resistance Perks are too strong, it was a surprise seeing it increase to x10 from x5 in the previous beta release, and even at x5 it's still too strong. This perk essentially makes ships have an effective HP way above their class, and even makes them tougher than your Starbase.

In addition, there is barely any effective Null-Type Weapons to counter tough ships with all 3 Resistance Perks installed. The only Null-Type weapons with any good damage utilizes clouds - such as Oblivion Cannon, Acid Cannon, and Heavy Acid Torpedo, but the issue here is that these weapons are most effective against non/slow moving targets, and most - if not all, ships don't tend to linger inside the clouds for more than 1 second.

**So here's what I propose, either:**
• Lower the value for the Resistance perks to (preferably) 50%, x1 HP value, just like in EH:RPG
• **Or**, add new Null-Type Weapons strong enough to deal significant damage to fast moving targets.

**Comment by vlad-ultramarine** [comment]
предлагаю ослабление перков на резист чтобы они давали 60 или 70%
![Screenshot_20240324-140827](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/76f9fb2b-8a63-4deb-86f3-919c399ae24a)

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/baac447d-eccb-48ff-87f2-4053b8fd26f7

**Comment by MisterN13** [comment]
Нормально там все с хп.

**Comment by PavelZinchenko** [comment]
It's at x5 currently. While it's powerful, it requires the use of all three upgrade slots, which might otherwise be used for another upgrades.

**Comment by Inedilarion** [comment]
Ну, если посмотреть на другие модификации:
Автонаведение и 0 задержки перезарядки щита совершенно бесполезны. Как и регенерация, на которую в условиях фронтира нету времени.
Модификация на вес корабля уже почти полностью утратила актуальность (потому что большинство нуждающихся в ней кораблей перестали в ней нуждаться при появлении новых двигателей)
Модификация на задержку перезарядки энергии очень специфическая, она подходит только очень большим кораблям с кучей места под реакторы. И даже так особого прироста боевой эффективности от неё добиться сложно. 
Модификация на любой тип оружия, которая может дать впечатляющий буст полезности бесполезным кораблям (во многом благодаря оружию C и L, очень сильному сравнительно с остальными пушками, но всё же).
И модификация бесконечные возрождения, которая не усиливает характеристик напрямую, но позволяет использовать мелочь и забить на ремонт

Если подвести итог, линкоры и титаны зачастую вообще не нуждаются ни в одной из указанных выше модификаций (если говорить о сильнейших их представителях, которыми и пользуются игроки) и модификации на сопротивление сразу дадут им х5 хп. А фрегаты и эсминцы используют модификацию на бесконечное возрождение, также некоторые используют модификацию на оружие, что позволяет защититься либо только от энергетического урона (то есть, от большинства сильнейшего оружия в игре), либо ещё и от теплового (что оставляет уязвимость только для святой пушки, которая в реалиях фронтира и так не очень актуальна из-за низкой дальности и скорости снаряда)

В общем, альтернатив использованию модификации на сопротивление очень мало, и они в основном на фрегатах и эсминцах. И даже с ними, использование 1-2 модификаций на сопротивление уже является очень значительной защитой

Well, if you look at other modifications:
Auto-targeting and 0 shield reload delay are completely useless. As well as regeneration, for which there is no time in frontier.
Modification for ship weight has almost completely lost its relevance (because most of the ships that needed it stopped needing it when new engines appeared)
The modification of 0 energy recharge delay is very specific; it is only suitable for very large ships with a lot of space for reactors. And even so, it is difficult to achieve a special increase in combat effectiveness from it.
A modification for any type of weapon that can give an impressive boost to the usefulness of useless ships (largely thanks to weapons C and L, which are very strong compared to other guns, but still).
And the endless revival modification, which does not directly enhance the characteristics, but allows you to use small change and forget about repairs

To summarize, battleships and titans often do not need any of the above modifications at all (if we talk about their strongest representatives, which are what players use) and resistance modifications will immediately give them x5 hp. And frigates and destroyers use a modification for endless rebirth, and some also use a modification for weapons, which allows you to protect either only from energy damage (that is, from most of the strongest weapons in the game), or also from heat (which leaves vulnerability only for the holy cannon , which in the realities of the frontier is not very relevant anyway due to the low range and speed of the projectile)

In general, there are very few alternatives to using the resistance modification, and they are mainly on frigates and destroyers. And even with them, the use of 1-2 resistance modifications is already a very significant protection

**Comment by IsmollCheeKen** [comment]
I agree with the Resist perks being put to x2 HP, it isn't too weak to be replaced by other perks, and it isn't too strong that it makes other perks weak.

**Comment by Zen9890** [comment]
> Resists at 10x may be perceived too high, but they are not. You have 3 perk choices and you need to sacrifice other things for them. Even if you have all 3 resist perks on one ship, you are still vulnerable to no-type-damage.
> 
> **High resist perks are necessary to allow players to counter new meta developments quickly!** Everyone is using HLCs, DR, HEW,....? => equip all your ships with energy resist perks and that's it! This, of course, does not work if the resist perks are too low like only 1-2 times the hp.
> 
> For this to work, it needs to be at the very least 5x hp.
> 
> IF... only IF resist perks do not effect resists to no-type-damge (it's half of lowest resist, iirc), then it would be even ok for the perks to give full immunity to 1 resit type, yes this is only a theoretical example, but that's how it's meant to be played out, rock paper scissor/shotgun, that's what the kids call meta...

Balancing OP stuff with OP perks is terrible idea

**Comment by TaipionsSalemClient** [comment]
> > Resists at 10x may be perceived too high, but they are not. You have 3 perk choices and you need to sacrifice other things for them. Even if you have all 3 resist perks on one ship, you are still vulnerable to no-type-damage.
> > **High resist perks are necessary to allow players to counter new meta developments quickly!** Everyone is using HLCs, DR, HEW,....? => equip all your ships with energy resist perks and that's it! This, of course, does not work if the resist perks are too low like only 1-2 times the hp.
> > For this to work, it needs to be at the very least 5x hp.
> > IF... only IF resist perks do not effect resists to no-type-damge (it's half of lowest resist, iirc), then it would be even ok for the perks to give full immunity to 1 resit type, yes this is only a theoretical example, but that's how it's meant to be played out, rock paper scissor/shotgun, that's what the kids call meta...
> 
> Balancing OP stuff with OP perks is terrible idea

it only looks OP to you, as you do not know any better,
in other games, giving full immunity to a damage type would be standard,
as a tool for the evolving meta and also for countering any op weapon (except maybe no-type weapons) this is a crucial tool to have!
